# This will be appended to the Dnsmasq config. This should primarily be
# used to specify wildcard DNS entries since they are not supported in
# /etc/hosts. See: https://stackoverflow.com/a/20446931

# OpenShift wildcard ingress
address=/apps.ocp.taco.moe/192.168.0.113
